#!/usr/bin/env python3
"""Generate MANIFEST.md, the single file an agent reads to select rule docs.

Without it an agent walks 11 category indexes to answer one question: which
leaf docs match this stack? The manifest answers it in one read, from the
`applies_to` frontmatter that is already authoritative.

It is generated, never hand-edited. `--check` fails when the committed file
differs from what the frontmatter implies, which is what CI and the pre-commit
hook run. A manifest that can drift from the corpus is worse than no manifest,
because an agent trusts it and stops looking.

    python3 scripts/gen_manifest.py           # write MANIFEST.md
    python3 scripts/gen_manifest.py --check   # exit 1 if stale
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "MANIFEST.md"

# Only classes an agent selects between. `annex` is gated on the task, and its
# parent already names it in `annex:`; `setup`/`never` are not project rules.
LISTED = ("always", "conditional", "task")

HEADER = """---
applies_to:
  load: "index"
  purpose: "the generated selection table for every loadable rule doc"
---
# Manifest

Generated by `scripts/gen_manifest.py`. Do not edit by hand; CI verifies it
against the `applies_to` frontmatter of every document.

An agent following the `AI.md` Loading Protocol reads this file once, then loads
only the rows whose condition matches the detected stack. It does not need to
open a category index.

- `always` rows load on every task.
- `conditional` rows load only when the condition holds.
- `task` rows load by task type, not by stack.
- A doc with an annex has a sibling `*.ANNEX.md`; load it only for the tasks its
  `tasks:` field names.
"""


def applies_to(path: Path) -> dict | None:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 3)
    if end == -1:
        return None
    try:
        meta = yaml.safe_load(text[4:end])
    except yaml.YAMLError:
        return None
    if not isinstance(meta, dict):
        return None
    at = meta.get("applies_to")
    return at if isinstance(at, dict) else None


def condition(meta: dict) -> str:
    """The narrowest human-readable statement of when this doc applies."""
    if meta.get("load") == "task":
        return "the task is " + " or ".join(f"`{t}`" for t in meta.get("tasks", []))
    for key in ("languages", "frameworks", "libraries", "tools"):
        if meta.get(key):
            vals = ", ".join(f"`{v}`" for v in meta[key])
            return f"{key}: {vals}"
    return meta.get("when", "-")


def rows() -> list[tuple[str, str, str, str, bool]]:
    out = []
    for p in sorted(ROOT.rglob("*.md")):
        if ".git" in p.parts or "node_modules" in p.parts:
            continue
        if p.name.endswith(".ANNEX.md"):
            continue
        meta = applies_to(p)
        if not meta or meta.get("load") not in LISTED:
            continue
        rel = p.relative_to(ROOT).as_posix()
        purpose = meta.get("purpose")
        if not purpose and meta["load"] != "always":
            raise SystemExit(f"{rel}: load: {meta['load']} needs a `purpose`; "
                             f"the manifest selects on it")
        out.append((rel, meta["load"], condition(meta),
                    purpose, bool(meta.get("annex"))))
    return out


def wrap(bullet: str, width: int = 100) -> str:
    """Wrap to satisfy markdownlint MD013, continuation lines indented two."""
    out, line = [], ""
    for word in bullet.split(" "):
        if line and len(line) + 1 + len(word) > width:
            out.append(line)
            line = "  " + word
        else:
            line = f"{line} {word}" if line else word
    out.append(line)
    return "\n".join(out)


def render() -> str:
    body = [HEADER.rstrip("\n")]
    for load in LISTED:
        sel = [r for r in rows() if r[1] == load]
        body.append(f"\n## {load} ({len(sel)})\n")
        for rel, _, cond, purpose, has_annex in sel:
            mark = " *(annex)*" if has_annex else ""
            if load == "always":
                # No selection decision to make, so the purpose buys nothing.
                body.append(f"- `{rel}`{mark}")
            else:
                body.append(wrap(f"- `{rel}`{mark} - {purpose}. Load when {cond}."))
    return "\n".join(body).rstrip("\n") + "\n"


def main() -> int:
    want = render()
    if "--check" in sys.argv:
        have = MANIFEST.read_text(encoding="utf-8") if MANIFEST.exists() else ""
        if have != want:
            print("MANIFEST.md is stale. Run: python3 scripts/gen_manifest.py")
            return 1
        print(f"manifest check passed: {len(rows())} docs")
        return 0
    MANIFEST.write_text(want, encoding="utf-8")
    print(f"wrote MANIFEST.md: {len(rows())} docs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
